name: docdial
description: "Doctor Appointment Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.4.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  location: ^7.0.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  svg_flutter: ^0.0.1
  iconsax: ^0.0.8
  stacked_card_carousel: ^0.0.4
  flutter_rating_stars: ^1.1.0
  easy_date_timeline: ^1.1.3
  popover: ^0.3.1
  bottom_bar: ^2.0.3
  quickalert: ^1.1.0
  flutter_shakemywidget: ^1.0.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/category/
    - assets/vector/
    - assets/logo/